USE [master]
GO

/****** Object:  Database [Aud]    Script Date: 8/10/2016 7:33:05 PM ******/
CREATE DATABASE [Aud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Aud', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Aud.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Aud_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Aud_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Aud] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Aud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Aud] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Aud] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Aud] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Aud] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Aud] SET ARITHABORT OFF 
GO

ALTER DATABASE [Aud] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Aud] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Aud] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Aud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Aud] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Aud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Aud] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Aud] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Aud] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Aud] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Aud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Aud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Aud] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Aud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Aud] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Aud] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Aud] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Aud] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Aud] SET  MULTI_USER 
GO

ALTER DATABASE [Aud] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Aud] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Aud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Aud] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Aud] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Aud] SET  READ_WRITE 
GO


