//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectoryDetail
    {
        public int Id { get; set; }
        public string IPAddress { get; set; }
        public string LDAPAddress { get; set; }
        public string DomainName { get; set; }
        public string ADUserName { get; set; }
        public string ADPassword { get; set; }
        public string Category { get; set; }
    }
}
