//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectoryUser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
        public string FirtName { get; set; }
        public string LastNamw { get; set; }
        public Nullable<int> ControlID { get; set; }
        public Nullable<int> ADD_ID { get; set; }
    
        public virtual Control Control { get; set; }
    }
}
