//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysappscript
    {
        public int ID { get; set; }
        public string AppName { get; set; }
        public string ScriptNum { get; set; }
        public Nullable<System.DateTime> ScriptDate { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
    }
}
