//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Workflow
    {
        public int CommentID { get; set; }
        public int ControlID { get; set; }
        public string StatusFrom { get; set; }
        public string StatusTo { get; set; }
        [DisplayFormat(DataFormatString = @"{0:MM\/dd\/yyyy}")]
        public System.DateTime ActionDate { get; set; }
        public string ActionBy { get; set; }
        public string Comments { get; set; }
        public string AssignedTo { get; set; }
    
        public virtual Control Control { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
